### ISSUE TITLE
Lint - Prettier version mismatch between CI and local dev

### ISSUE THREAD

**Issue by perryr16** [SEED-platform/seed#5012]
**Describe the bug**
When the CI runs it uses the perttier version specified in /.pre-commit-config.yaml. See `rev` below
```
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
```

The package.json file specifies a different version of prettier
```
    "prettier": "^3.5.2",
```

Running pre-commit run --all-files locally produced different results than when the CI ran due to the version mismatch (specifically in file /seed/docs/faq/featuers/get-general-info.md). These two versions should probably be aligned

You can get around this by explicitly specifying the version of prettier in the command when running locally
```
npx prettier@4.0.0-alpha.8 -w .
```
